export { default as IMG01} from '../../../assets/images/invoices-icon5.svg';
export { default as IMG02} from '../../../assets/images/profiles/avatar-04.jpg';
export { default as IMG03} from '../../../assets/images/profiles/avatar-06.jpg';
export { default as IMG04} from '../../../assets/images/profiles/avatar-08.jpg';
export { default as IMG05} from '../../../assets/images/profiles/avatar-10.jpg';
export { default as IMG06} from '../../../assets/images/profiles/avatar-11.jpg';
export { default as IMG07} from '../../../assets/images/profiles/avatar-09.jpg';
export { default as IMG08} from '../../../assets/images/profiles/avatar-12.jpg';
export { default as IMG09} from '../../../assets/images/profiles/avatar-03.jpg';